### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by rdebath** [JinweiClarkChao/brainfuck#2]
This brainfuck "Hello World!" fails to run correctly. You have a problem with your loops.

```brainfuck
>++++++++[<+++++++++>-]<.>>+>+>++>[-]+<[>[->+<<++++>]<<]>.+++++++..+++.>
->+++++++.<+[>[+>]>]<<<+++++++++++++++.>>.+++.------.--------.>>+.>++++.
```

**Comment by JinweiClarkChao** [comment]
Oops, I will fix it later

**Comment by JinweiClarkChao** [comment]
@rdebath fixed now.(Although my code looks too verbose now)

Any complex brainfuck test is welcome!:smiley:

**Comment by JinweiClarkChao** [comment]
@rdebath I tried several tests from [your project](https://github.com/rdebath/Brainfuck/tree/master/testing), only to found that my implementation is too verbose and slow :(
Obviously, my toy implementation of brainfuck needs to be improved. :)

**Comment by rdebath** [comment]
Yes, the brackets do spoil it; I've tried it like below, it might be small, but it's rather messy.
```c
case '[': if(t[m]==0)while((i+=(*p=='[')-(*p==']'))&&p[1])p++;break;
```
A stack seems to make the ']' command look neater (and faster) but doesn't help with '['. As far as I can see the _nicest_ way seems to be to precalculate where the loops will jump to (ie: 'compile' them) but that makes the who thing quite a bit larger.

As for tests, there are a few around eg: https://github.com/rdebath/Brainfuck/tree/master/testing

Though you'll have to change how you enter the program to run most of them.

FYI: the whole thing ...
```c
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
int main (int argc, char *argv[]) {
    char *b=0, *p, t[65536]={0};
    unsigned short m=0;
    int i=0;
    FILE *fp=argc>1?fopen(argv[1], "r"):stdin;
    size_t r=0;
    if(!fp || getdelim(&b,&r,argc>1?'\0':'!',fp)<0)
        perror(argv[1]);
    else if(b&&r>0)for(p=b;*p;p++)switch(*p) {
        case '>': m++;break;
        case '<': m--;break;
        case '+': t[m]++;break;
        case '-': t[m]--;break;
        case '.': putchar(t[m]);break;
        case ',': {int c=getchar();if(c!=EOF)t[m]=c;}break;
        case '[': if(t[m]==0)while((i+=(*p=='[')-(*p==']'))&&p[1])p++;break;
        case ']': if(t[m]!=0)while((i+=(*p==']')-(*p=='['))&&p>b)p--;break;
    }
    return 0;
}
```

**Comment by rdebath** [comment]
Yes, well Tritium, it's a whole other matter. That is one HUGE program for a BF interpreter. It doesn't count most of the time :-)

This one might though: https://github.com/rdebath/Brainfuck/blob/deadbeef/deadbeef.c
